replicaCount: 1

webapp:
  name: credit-viewer
  group: credit-viewer
  path: /
  tls:
    fqdn: credit-viewer.k8s.ucar.edu
    secretName: incommon-cert-credit-viewer
  container: 
    image: docker.io/mattrncar/credit-viewer-backend:v1
    port: 8000
    memory: 1G
    cpu: 2
