services:
  credit-viewer-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    platform: linux/amd64
    container_name: credit-viewer-backend
    ports:
      - "8000:8000"

  credit-viewer-nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    platform: linux/amd64
    container_name: credit-viewer-nginx
    ports:
      - "8080:80"
    depends_on:
      - credit-viewer-backend
